# Site settings
title: "Ed Fazli's Technical Blog"
email: <your-email>@example.com
description: >-
  Professional technical blog covering software development, cloud computing,
  DevOps, and emerging technologies. Insights from a seasoned developer.
baseurl: ""
url: "https://edfazli.github.io" # Default GitHub Pages domain
twitter_username: <your-twitter>
github_username: EdFazli
linkedin_username: <your-linkedin>

# Author information
author:
  name: "Ed Fazli"
  bio: "Software Developer & Technical Writer"
  avatar: "/assets/images/profile.jpg"
  location: "Your Location"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/EdFazli"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/<your-profile>"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/<your-handle>"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Contents"
      toc_icon: "cog"

# SEO and Analytics
google_analytics: # Add your GA tracking ID
google_site_verification: # Add your verification code

# Comments (using Disqus)
comments:
  provider: "disqus"
  disqus:
    shortname: # Add your Disqus shortname

# Social sharing
twitter:
  username: <your-twitter>

# Reading time
read_time: true
words_per_minute: 200

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .gitignore

# Include
include:
  - _pages

# Sass
sass:
  sass_dir: _sass
  style: compressed
